publish_to: none

name: ride_hailing_server
description: Ride-hailing app server using Serverpod
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  serverpod: ^2.1.0
  serverpod_auth_server: ^2.1.0
  mongo_dart: ^0.10.3
  flutter_stripe: ^11.5.0
  mailer: ^6.0.1
  crypto: ^3.0.3
  jwt_decoder: ^2.0.1
  geolocator: ^10.1.0
  uuid: ^4.2.1
  bcrypt: ^1.1.3
  redis: ^4.0.0
  json_annotation: ^4.8.1
  http: ^1.1.0
  ride_hailing_shared:
    path: ../shared

dev_dependencies:
  serverpod_cli: ^2.1.0
  test: ^1.24.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  mocktail: ^1.0.1

serverpod:
  runmode: development
